### ISSUE TITLE
add a category page (home page)

### ISSUE THREAD

**Issue by oladhari** [oladhari/e-commerce#10]
**checklist:**

- [x] create a branch `feat/10_home_page`
- [x] add a banner with title `Svaria Market`
- [x] and list the categories from API (let fetching for @oladhari )

**Comment by Farid212** [comment]
done

**Comment by oladhari** [comment]
@Farid212 really so fast ! thank you
can not review now, I am so tired, let is review tomorrow! thank you for your great work!
